// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3LbuC5MKTOvM8KKKcWPX9cHaN-qBJpZM',
    appId: '1:396663315657:web:002105a59de174f0c0c118',
    messagingSenderId: '396663315657',
    projectId: 'chat-app-2025-9790f',
    authDomain: 'chat-app-2025-9790f.firebaseapp.com',
    storageBucket: 'chat-app-2025-9790f.firebasestorage.app',
    measurementId: 'G-Z09DS75QMV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNsHBy2WOMgYv9Xhq_cL5pYSxadlZPvdM',
    appId: '1:396663315657:android:84d6a455d79b70d8c0c118',
    messagingSenderId: '396663315657',
    projectId: 'chat-app-2025-9790f',
    storageBucket: 'chat-app-2025-9790f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEWVmOTihx2dRysJZoRYa9Bcy7sGvOMHo',
    appId: '1:396663315657:ios:1a7eaa2e4b8f7361c0c118',
    messagingSenderId: '396663315657',
    projectId: 'chat-app-2025-9790f',
    storageBucket: 'chat-app-2025-9790f.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEWVmOTihx2dRysJZoRYa9Bcy7sGvOMHo',
    appId: '1:396663315657:ios:1a7eaa2e4b8f7361c0c118',
    messagingSenderId: '396663315657',
    projectId: 'chat-app-2025-9790f',
    storageBucket: 'chat-app-2025-9790f.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3LbuC5MKTOvM8KKKcWPX9cHaN-qBJpZM',
    appId: '1:396663315657:web:816e2e08e732afffc0c118',
    messagingSenderId: '396663315657',
    projectId: 'chat-app-2025-9790f',
    authDomain: 'chat-app-2025-9790f.firebaseapp.com',
    storageBucket: 'chat-app-2025-9790f.firebasestorage.app',
    measurementId: 'G-GZ8ZF7PD0L',
  );
}
